### ISSUE TITLE
Make a course for setting up SSO

### ISSUE THREAD

**Issue by saulrobe** [argoproj-labs/training-material#39]
Hello,

It be great if there was a course that shows how to set up SSO. Possibly, the connecting to an Argo CD Dex (https://argoproj.github.io/argo-workflows/argo-server-sso-argocd/).

I just have been struggling with the SSO, and thought this would be good for training. I think the thing I am having the most issues now is with the service accounts and how those are deployed and how users are attached to them.

A training course that showed this would be very helpful!

**Comment by tico24** [comment]
The problem is this requires external things to auth against and actual secrets. That's why it's not here. 

Serviceaccount stuff is more K8s training in my opinion.
