### ISSUE TITLE
"Using the CLI” page negates everything I learnt in earlier pages!

### ISSUE THREAD

**Issue by bikram-agarwal** [argoproj-labs/training-material#57]
Hi Team. Please accept this as a feedback.

I am currently going thorough [Interactive Training Material](https://killercoda.com/argoproj/course/argo-workflows/) for Argo.
In the first couple of pages, I learnt that the workflow’s yml file

> consists of one or more templates, one of which is defined as the entrypoint.

Cool. I carried out those steps alongside the tutorial. So far so good.

Next I reach the “Using the CLI” page, and there it executes the [hello-world.yaml](https://raw.githubusercontent.com/argoproj/argo-workflows/master/examples/hello-world.yaml) hosted on argoproj’s GitHub. And this yaml is thousands of lines long… and there are no templates: or entrypoint in it!!

So, I’m pretty baffled at this point. I’m probably missing a whole lot of things in between. But I was thinking this is step-by-step interactive tutorial. So, everything I learnt before this “Using the CLI” page… feels like it threw it out the window. :man-shrugging:

**Comment by tico24** [comment]
> And this yaml is thousands of lines long… and there are no templates: or entrypoint in it!!

Can you elaborate? The hello world yaml is 17 lines and does contain templates and an entrypoint?
