### ISSUE TITLE
Can't exit from the VIM editor in the web terminal

### ISSUE THREAD

**Issue by CannedFish** [argoproj-labs/training-material#6]
Hi, all, thanks for your work first.

I met a problem that when I try to finish the exercise by using the VIM editor to change an example, I can't find a way to save and exit the VIM editor.
More specifically, after I enter the insert mode and make some change, I can't exit to the normal mode by press [Esc], since I just lost the focus of the web terminal.

If you already know this issue, please teach me how to resolve this problem.
Or, hope this issue can help you make this project better.

**Comment by tico24** [comment]
This course has now moved to killercoda so the whole environment has changed. As a result, I will close this issue.
