### ISSUE TITLE
Issues with Argo UI 

### ISSUE THREAD

**Issue by jchillin** [argoproj-labs/training-material#62]
<img width="340" alt="image" src="https://github.com/user-attachments/assets/d58a9c67-45d2-40c8-ab9d-2376e1113a9d">
When trying to access the argo-server UI. I encounter a bad gateway error every time. I am on Mac using Chrome Version 128.0.6613.138 (Official Build) (arm64).

**Comment by tico24** [comment]
We don't have nginx in the mix so this would appear to be a killercoda bug. 

I have seen this before and unfortunately the fix is "wait a bit and try again". Sorry
