### ISSUE TITLE
Docker/whalesay does not work locally - plus can't get the https to work locally

### ISSUE THREAD

**Issue by mskem-reify** [argoproj-labs/training-material#65]
Trying to follow this tutorial locally, I didn't manage to access the argo server as the https reroute didn't work. I ended up only removing the login like so 
```
kubectl patch deployment \
  argo-server \
  --namespace argo \
  --type='json' \
  -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/args", "value": [
  "server",
  "--auth-mode=server"
]}]'
```

Also, the flow with docker/whalesay does not compile anymore so maybe use another example

**Comment by tico24** [comment]
> Also, the flow with docker/whalesay does not compile anymore so maybe use another example

We would welcome a pull requests for this. I notice upstream argo workflows also switched away from whalesay fairly recently.
