### ISSUE TITLE
Templates Scenario needs to be updated for Hooks

### ISSUE THREAD

**Issue by zdbasset** [argoproj-labs/training-material#9]
Nice tutorials but the last part of the Templates scenario demonstrates `onExit`. 
The doc say `onExit` is "DEPRECATED: Use Hooks[exit].Template instead."

**Comment by tico24** [comment]
I can't find this in the docs, can you please provide a reference?

Hooks in general are... pretty poor. I wouldn't **personally** recommend anyone uses them in prod.

**Comment by zdbasset** [comment]
Um…wow…I posted that over 2 years ago. To be honest, I no longer remember the details of the issue.
Maybe just consider it dead?

-David-

--
David R. Steiner
Virtualization Lead/System Administrator
Infrastructure Services
Information, Technology & Consulting
Dartmouth College
Hanover, NH. 03755
Phone: 603.646.3127

From: Tim Collins ***@***.***>
Date: Tuesday, November 28, 2023 at 9:44 AM
To: argoproj-labs/training-material ***@***.***>
Cc: David R. Steiner ***@***.***>, Author ***@***.***>
Subject: Re: [argoproj-labs/training-material] Templates Scenario needs to be updated for Hooks (#9)

I can't find this in the docs, can you please provide a reference?

Hooks in general are... pretty poor. I wouldn't personally recommend anyone uses them in prod.

**Comment by tico24** [comment]
Yeah, no probs. I've just taken over the repo after moving everything to Killercoda, so just doing housekeeping.
